apiVersion: apps/v1
kind: Deployment
metadata:
  name: ec2-pipeline-deployment
spec:
  selector:
    matchLabels:
      app: ec2-pipeline
  replicas: 3 # tells deployment to run 3 pods matching the template
  template:
    metadata:
      labels:
        app: ec2-pipeline
    spec:
      containers:
      - name: ec2-pipeline-container
        image: kcharette/ec2-pipeline
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: ec2-pipeline-service
spec:
  type: NodePort
  selector:
    app: ec2-pipeline
  ports:
  - protocol: "TCP"
    port: 8090
    targetPort: 8090
    nodePort: 30007
 